### PR TITLE
OAuth2 client implementation review

### PR DESCRIPTION
**Pull request by ateska**

### CODE REVIEW

**Comment by PremyslCerny** [comment]
Looks good.

**Comment by ateska** [comment]
@PremyslCerny - pls, one more review & merge it, pls.

**Comment by SukiCZ** [comment]
@ateska There are few issues in flake8. Could you pls fix them?

```
asab/web/accesslog.py:32:4: E265 block comment should start with '# '
asab/web/accesslog.py:34:3: E101 indentation contains mixed spaces and tabs
asab/web/authn/oauth/service.py:4:1: E302 expected 2 blank lines, found 1
asab/web/authn/oauth/service.py:19:35: E261 at least two spaces before inline comment
asab/web/authn/oauth/method.py:17:3: E265 block comment should start with '# '
asab/web/authn/oauth/method.py:21:92: W291 trailing whitespace
asab/web/authn/oauth/method.py:24:98: W291 trailing whitespace
asab/web/authn/oauth/method.py:27:24: W291 trailing whitespace
asab/web/authn/oauth/method.py:31:1: W293 blank line contains whitespace
asab/web/authn/oauth/method.py:37:1: W293 blank line contains whitespace
asab/web/authn/oauth/middleware.py:4:1: F401 'pprint' imported but unused
asab/web/authn/oauth/middleware.py:58:68: F821 undefined name 'oauth_server_id'
```

Thanks :green_heart:

**Comment by ateska** [comment]
> @ateska There are few issues in flake8. Could you pls fix them?
> 
> ```
> asab/web/accesslog.py:32:4: E265 block comment should start with '# '
> asab/web/accesslog.py:34:3: E101 indentation contains mixed spaces and tabs
> asab/web/authn/oauth/service.py:4:1: E302 expected 2 blank lines, found 1
> asab/web/authn/oauth/service.py:19:35: E261 at least two spaces before inline comment
> asab/web/authn/oauth/method.py:17:3: E265 block comment should start with '# '
> asab/web/authn/oauth/method.py:21:92: W291 trailing whitespace
> asab/web/authn/oauth/method.py:24:98: W291 trailing whitespace
> asab/web/authn/oauth/method.py:27:24: W291 trailing whitespace
> asab/web/authn/oauth/method.py:31:1: W293 blank line contains whitespace
> asab/web/authn/oauth/method.py:37:1: W293 blank line contains whitespace
> asab/web/authn/oauth/middleware.py:4:1: F401 'pprint' imported but unused
> asab/web/authn/oauth/middleware.py:58:68: F821 undefined name 'oauth_server_id'
> ```
> 
> Thanks 💚

Not introduced by my code. I will try to fix what I can ...

**Pull request merged**
