### PR TITLE
Rewrite warning message : Zookeeper wrapper get-data

### PR DESCRIPTION
**Pull request by mithunbharadwaj**

### CODE REVIEW

**Comment by mithunbharadwaj** [comment]
output from testing

`29-Jun-2022 13:22:48.823635 WARNING asab.zookeeper Getting the data from Zookeeper node '/asabconfigtest/config/Sidebar/LogMan.ioq.json' failed`

**Comment by mithunbharadwaj** [comment]
@ateska I should change warning message for all wrapper methods.

**Comment by ateska** [comment]
> @ateska I should change warning message for all wrapper methods.

Sure.

**Comment by mithunbharadwaj** [comment]
@ateska I can merge this I suppose!

**Pull request merged**
