### PR TITLE
Makedocs documentation

### PR DESCRIPTION
**Pull request by mejroslav**
## Screenshots

Home page
image

Example of inline code annotations
image

Example of autodocs
image

You can see a source code for each class / method
image

Examples are stored in dedicated tab
image

### CODE REVIEW

**Review by ateska — APPROVED** [review]
Ok. Let's merge it but we need to create a CI/CD for a deployment of this to docs.teskalabs.com

**Comment by ateska** [comment]
Colours etc. should be unified with the rest of our new documentation.

**Comment by ateska** [comment]
Ok, this is ready to be merged ... and switched from readthedocs to our site.

**Comment by mejroslav** [comment]
> Ok, this is ready to be merged ... and switched from readthedocs to our site.
I'm going to do it very carefully...

**Pull request merged**
