### PR TITLE
asab-zookeeper : unadvertise if application is already advertised

### PR DESCRIPTION
**Pull request by mithunbharadwaj**

### CODE REVIEW

**Comment by PremyslCerny** [comment]
@mithunbharadwaj Looks good. But please make sure it is tested, that f. e. after 15 minutes there is still only one record in ZK in run.

**Review by PremyslCerny — APPROVED** [review]

**Comment by mithunbharadwaj** [comment]
I have been running it for 90 minutes. There is a single copy only. Looks good so far.

**Comment by PremyslCerny** [comment]
@mithunbharadwaj I guess it could be merged then, right @ateska ?

**Comment by mithunbharadwaj** [comment]
is a necessity to delete a z-node and create another one if a duplicate exists or the current way of the working mechanism is good enough.?

**Review by ateska — APPROVED** [review]
Ok, good from my side, let's see if this resolves the issue.

**Pull request merged**
