### PR TITLE
Fix the problem with sessions in ASAB Storage for ElasticSearch

### PR DESCRIPTION
**Pull request by ateska**
Issues:

- [x] `File "/home/eliska/teskalabs/asab/asab/storage/elasticsearch.py", line 586, in put_policy`.
        `TypeError: ssl should be SSLContext, bool, Fingerprint or None, got <class 'ssl.SSLContext'> instead.`  
        Typo.

- [x] `async with self.ESStorageService.session().request(method="GET", url=url, headers={`
        `AttributeError: 'StorageService' object has no attribute 'session'`. 

- [ ] 409 in `_update_existing_object` http://gitlab.teskalabs.int/team/grey/-/issues/1086
- [ ] 400 in `_update_existing_object` http://gitlab.teskalabs.int/team/grey/-/issues/1084

### CODE REVIEW

**Comment by ateska** [comment]
Tested by:

```
asab/examples % PYTHONPATH=.. python3 ./storage_elasticsearch.py
```

**Comment by mithunbharadwaj** [comment]
@ateska I've encountered an issue during testing watcher that appears to be a breaking change introduced by this MR. The application throws an exception during the initialization of the lookup index template in ElasticSearch. 

`06-Nov-2023 16:08:51.951775 ERROR lmiowatcher.app Unexpected exception occurred when initializing lookup index template in ElasticSearch: 'StorageService' object has no attribute 'session'.`

This error suggests that the StorageService object is missing the session attribute, which is likely expected to be present.

**Comment by eliska-n** [comment]
> @ateska I've encountered an issue during testing watcher that appears to be a breaking change introduced by this MR. The application throws an exception during the initialization of the lookup index template in ElasticSearch.
> 
> `06-Nov-2023 16:08:51.951775 ERROR lmiowatcher.app Unexpected exception occurred when initializing lookup index template in ElasticSearch: 'StorageService' object has no attribute 'session'.`
> 
> This error suggests that the StorageService object is missing the session attribute, which is likely expected to be present.

Can you share the traceback?

**Comment by mithunbharadwaj** [comment]
@eliska-n 

`BitSwan BSPump version devel
07-Nov-2023 03:35:00.948027 ERROR lmiowatcher.app Unexpected exception occurred when initializing lookup index template in ElasticSearch: ''StorageService' object has no attribute 'session''.
Traceback (most recent call last):
  File "/Users/mithunshuvashankar/PycharmProjects/lmio-watcher/lmiowatcher/app.py", line 157, in initialize_lookup_index_template
    async with self.ESStorageService.session().request(method="GET", url=url, headers={
AttributeError: 'StorageService' object has no attribute 'session'
`

**Comment by ateska** [comment]
> Testing in the depositor... @ateska
> 
> ```
> 06-Nov-2023 15:52:06.159605 NOTICE lmiodepositor.app Updating ILM policy for event lane '/EventLanes/default.yaml' -> 'eliska-test'.
> 06-Nov-2023 15:52:06.160012 ERROR lmiodepositor.app The following exception occurred when updating ILM for event lane '/EventLanes/default.yaml': 'ssl should be SSLContext, bool, Fingerprint or None, got <class 'ssl.SSLContext'> instead.'
> Traceback (most recent call last):
>   File "/home/eliska/teskalabs/lmio-depositor/lmiodepositor/app.py", line 346, in _create_ilm_for_event_lane
>     await self.StorageService.put_policy(policy_name, policy)
>   File "/home/eliska/teskalabs/asab/asab/storage/elasticsearch.py", line 586, in put_policy
>     async with session.put(
>   File "/home/eliska/teskalabs/venvs/asab/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
>     self._resp = await self._coro
>   File "/home/eliska/teskalabs/venvs/asab/lib/python3.10/site-packages/aiohttp/client.py", line 402, in _request
>     ssl = _merge_ssl_params(ssl, verify_ssl, ssl_context, fingerprint)
>   File "/home/eliska/teskalabs/venvs/asab/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 192, in _merge_ssl_params
>     raise TypeError(
> TypeError: ssl should be SSLContext, bool, Fingerprint or None, got <class 'ssl.SSLContext'> instead.
> ```

Fixed

**Comment by ateska** [comment]
> I don't like these defaults really. When I don't configure elasticsearch_url, it is looking of ES on localhost.
> 
> ```
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/eliska/teskalabs/lmio-depositor/lmiodepositor/app.py", line 122, in reload_pipelines
>     await self._create_indices_if_not_exists_for_event_lane()
>   File "/home/eliska/teskalabs/lmio-depositor/lmiodepositor/app.py", line 375, in _create_indices_if_not_exists_for_event_lane
>     indices_description = await self.StorageService.indices()
>   File "/home/eliska/teskalabs/asab/asab/storage/elasticsearch.py", line 535, in indices
>     raise Exception("Failed to connect to '{}'".format(url))
> Exception: Failed to connect to 'http://localhost:9200/'
> ```

@eliska-n what default do you expect then?

**Comment by ateska** [comment]
Here is another round of refactoring:

- I unified the way how ElasticSearch requests are handled by `request()` method
- I removed `scroll()` method, it was broken and if anyone wants to use it, it has to be recreated anyway\

@mithunbharadwaj 

>06-Nov-2023 16:08:51.951775 ERROR lmiowatcher.app Unexpected exception occurred when initializing lookup index
> template in ElasticSearch: 'StorageService' object has no attribute 'session'.

LMIO Watcher has to be updated to `request()` now.

**Comment by mithunbharadwaj** [comment]
@ateska I will refactor 

I will update watcher to use request() now and test.

**Comment by eliska-n** [comment]
> > I don't like these defaults really. When I don't configure elasticsearch_url, it is looking of ES on localhost.
> > ```
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> >   File "/home/eliska/teskalabs/lmio-depositor/lmiodepositor/app.py", line 122, in reload_pipelines
> >     await self._create_indices_if_not_exists_for_event_lane()
> >   File "/home/eliska/teskalabs/lmio-depositor/lmiodepositor/app.py", line 375, in _create_indices_if_not_exists_for_event_lane
> >     indices_description = await self.StorageService.indices()
> >   File "/home/eliska/teskalabs/asab/asab/storage/elasticsearch.py", line 535, in indices
> >     raise Exception("Failed to connect to '{}'".format(url))
> > Exception: Failed to connect to 'http://localhost:9200/'
> > ```
> 
> @eliska-n what default do you expect then?

I'm not too fond of these defaults really. I understand the importance of reasonable defaults, but assuming ES on localhost:9200 is..meh... We had this discussion with zookeeper. (There was a default leading to our lmio-box zookeeper, which was even more evil). I had this discussion with Elena already as she will do the configurations - let's discuss it on review, please.

**Comment by mithunbharadwaj** [comment]
```
10-Nov-2023 10:55:59.621577 ERROR lmiowatcher.processor During update of item '45.77.250.80' in lookup with ID 'ip_ref.default', an exception occurred: 'Unexpected response code: 409'
Traceback (most recent call last):
  File "/app/lmio-watcher/lmiowatcher/processor.py", line 118, in generate
    await self.ContentService.update_item(lookup_id, _id, data, upsert=True)
  File "/app/lmio-watcher/lmiowatcher/content/service.py", line 182, in update_item
    await cre.execute()
  File "/usr/local/lib/python3.7/site-packages/asab/storage/elasticsearch.py", line 426, in execute
    return await self._update_existing_object()
  File "/usr/local/lib/python3.7/site-packages/asab/storage/elasticsearch.py", line 477, in _update_existing_object
    raise ConnectionError("Unexpected response code: {}".format(resp.status))
ConnectionError: Unexpected response code: 409
```

I'm not sure of the exact cause, but it seems like handling version conflicts in Elasticsearch could be a potential solution. Any insights or suggestions on this would be greatly appreciated.

**Comment by mithunbharadwaj** [comment]
I've encountered an AttributeError in the asab.storage.elasticsearch module, specifically in the get method at line 166. The issue arises because a string object is being accessed as if it were a dictionary, causing the error: 'str' object has no attribute 'get'. This suggests that the resp variable, expected to be a dictionary-like object, is actually a string at this point in the code. It seems there might be a mismatch in the expected response format from an Elasticsearch operation or an issue in response processing.

`10-Nov-2023 10:51:32.369074 ERROR lmiowatcher.content.service Exception 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/lmio-watcher/lmiowatcher/content/service.py", line 72, in get_item
    response = await self.ESStorageService.get("{}.lkp".format(index).lower(), key)
  File "/usr/local/lib/python3.7/site-packages/asab/storage/elasticsearch.py", line 166, in get
    resp.get("error", {}).get("reason")
AttributeError: 'str' object has no attribute 'get'
`

**Comment by ateska** [comment]
> I've encountered AttributeError in the asab.storage.elasticsearch module, specifically in the get method at line 166. The issue arises because a string object is being accessed as if it were a dictionary, causing the error: 'str' object has no attribute 'get'. I reckon the resp variable, expected to be a dictionary-like object, is actually a string at this point in the code. It seems there might be a mismatch in the expected response format from an Elasticsearch operation or an issue in response processing.
> 
> `10-Nov-2023 10:51:32.369074 ERROR lmiowatcher.content.service Exception 'str' object has no attribute 'get' Traceback (most recent call last): File "/app/lmio-watcher/lmiowatcher/content/service.py", line 72, in get_item response = await self.ESStorageService.get("{}.lkp".format(index).lower(), key) File "/usr/local/lib/python3.7/site-packages/asab/storage/elasticsearch.py", line 166, in get resp.get("error", {}).get("reason") AttributeError: 'str' object has no attribute 'get' `

ElasticSearch responds in JSON, check your configuration, please.

**Comment by ateska** [comment]
> ```
> 10-Nov-2023 10:55:59.621577 ERROR lmiowatcher.processor During update of item '45.77.250.80' in lookup with ID 'ip_ref.default', an exception occurred: 'Unexpected response code: 409'
> Traceback (most recent call last):
>   File "/app/lmio-watcher/lmiowatcher/processor.py", line 118, in generate
>     await self.ContentService.update_item(lookup_id, _id, data, upsert=True)
>   File "/app/lmio-watcher/lmiowatcher/content/service.py", line 182, in update_item
>     await cre.execute()
>   File "/usr/local/lib/python3.7/site-packages/asab/storage/elasticsearch.py", line 426, in execute
>     return await self._update_existing_object()
>   File "/usr/local/lib/python3.7/site-packages/asab/storage/elasticsearch.py", line 477, in _update_existing_object
>     raise ConnectionError("Unexpected response code: {}".format(resp.status))
> ConnectionError: Unexpected response code: 409
> ```
> 
> I'm not sure of the exact cause, but it seems like handling version conflicts in Elasticsearch could be a potential solution. Any insights or suggestions on this would be greatly appreciated.

I need to be able to reproduce this first, then we can develop a solution to this issue.

**Comment by mithunbharadwaj** [comment]
@ateska 

`13-Nov-2023 16:52:56.654596 ERROR lmiowatcher.processor During update of item '169.254.0.0/16' in lookup with ID 'ip_ref.default', an exception occurred: 'Unexpected response code: 400'
Traceback (most recent call last):
  File "/app/lmio-watcher/lmiowatcher/processor.py", line 118, in generate
    await self.ContentService.update_item(lookup_id, _id, data, upsert=True)
  File "/app/lmio-watcher/lmiowatcher/content/service.py", line 182, in update_item
    await cre.execute()
  File "/usr/local/lib/python3.7/site-packages/asab/storage/elasticsearch.py", line 426, in execute
    return await self._update_existing_object()
  File "/usr/local/lib/python3.7/site-packages/asab/storage/elasticsearch.py", line 477, in _update_existing_object
    raise ConnectionError("Unexpected response code: {}".format(resp.status))
ConnectionError: Unexpected response code: 400`

**Pull request merged**
